name: Test Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Initialize Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.12'

      - name: Install package
        run: |
          python3 -m pip install --editable .[test,docs]

      - name: Run pytest tests
        run: |
          pytest

      - name: Run coverage
        run: |
          pytest --cov=phenopacket_mapper
